package com.google.android.gms.common.package_12.internal;

import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.internal.Preconditions;
import com.google.android.gms.common.package_12.PendingResult.StatusListener;
import com.google.android.gms.common.package_12.ResultCallback;
import com.google.android.gms.common.package_12.ResultTransform;
import com.google.android.gms.common.package_12.Status;
import com.google.android.gms.common.package_12.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zacp<R extends com.google.android.gms.common.api.Result>
  extends PendingResult<R>
{
  private final Status status;
  
  public zacp(Status paramStatus)
  {
    Preconditions.checkNotNull(paramStatus, "Status must not be null");
    Preconditions.checkArgument(paramStatus.isSuccess() ^ true, "Status must not be success");
    status = paramStatus;
  }
  
  public final void addStatusListener(PendingResult.StatusListener paramStatusListener)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final com.google.android.gms.common.package_12.Result await()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final com.google.android.gms.common.package_12.Result await(long paramLong, TimeUnit paramTimeUnit)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void cancel()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final boolean isCanceled()
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  final Status read()
  {
    return status;
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final void setResultCallback(ResultCallback paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
  
  public final TransformedResult then(ResultTransform paramResultTransform)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
}
